version: '3.8'

services:
  # PostgreSQL база данных
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mmorpg_board
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis для кеширования и Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django веб-приложение
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mmorpg_board
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./logs:/app/logs
    restart: unless-stopped

  # Celery worker для обработки задач
  celery:
    build: .
    command: celery -A mmorpg_board worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mmorpg_board
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./logs:/app/logs
    restart: unless-stopped

  # Celery beat для периодических задач
  celery-beat:
    build: .
    command: celery -A mmorpg_board beat --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mmorpg_board
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./logs:/app/logs
    restart: unless-stopped

  # Nginx для раздачи статики (опционально)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
      - ./media:/media:ro
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 